# .gitlab-ci.yml

stages:
  - test
  - deploy

variables:
  DATABASE_URL: "sqlite:///db.sqlite3"

before_script:
  # Install dependencies
  - pip install -r requirements.txt
  # Apply migrations
  - python manage.py migrate

test:
  stage: test
  script:
    - python manage.py test

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - # Add deployment commands here
  only:
    - main
